# GoReleaser configuration for torn_rw_stats
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    # Run tests before building
    - go test ./...

builds:
  - id: torn_rw_stats
    main: .
    binary: torn_rw_stats

    # Build for multiple platforms
    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    # Windows doesn't need arm64
    ignore:
      - goos: windows
        goarch: arm64

    # Build flags
    env:
      - CGO_ENABLED=0

    flags:
      - -a
      - -installsuffix=cgo

    ldflags:
      - -s -w
      - -extldflags "-static"

archives:
  - id: torn_rw_stats
    format: tar.gz

    # Use zip for Windows
    format_overrides:
      - goos: windows
        format: zip

    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  # For non-tag builds (main branch)
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge remote-tracking branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Refactors
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Other changes
      order: 999

release:
  github:
    owner: mnuck
    name: torn_rw_stats

  # Draft releases for review before publishing
  draft: false

  # Replace existing release if it exists (for latest)
  replace: false

  # Release header
  header: |
    ## Torn RW Stats {{ .Tag }}

    Download the appropriate binary for your platform below.

  # Release footer
  footer: |
    **Full Changelog**: https://github.com/mnuck/torn_rw_stats/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Container Images

    Multi-platform container images are also available:

    ```bash
    docker pull ghcr.io/mnuck/torn_rw_stats:{{ .Tag }}
    docker pull ghcr.io/mnuck/torn_rw_stats:latest
    ```

# Announcement templates
announce:
  skip: true
