---
apiVersion: v1
kind: Service
metadata:
  name: torn-rw-stats-service
  namespace: default
  labels:
    app: torn-rw-stats
spec:
  # Headless service for DNS resolution (no load balancing needed)
  clusterIP: None
  selector:
    app: torn-rw-stats
  # No ports defined since this is a batch application without HTTP endpoints
